name: Testing Pipeline

on:
  push:
    branches:
      - main  # Replace with your main branch name
  pull_request:
    branches:
      - main  # Replace with your main branch name

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # You can add steps here to install dependencies, build your code, and run tests
      # Example:
      # - name: Install dependencies
      #   run: npm install

      # - name: Build code
      #   run: npm run build

      # - name: Run tests
      #   run: npm test

      # Example placeholder step to ensure no errors occur
      - name: Ensure no errors
        run: echo "No errors found!"

      # Add more steps as needed based on your specific project requirements



